progetto_docker: "progetto_menu"
destinazione: "/opt"
modalita_developer: false
package_update: true

utility_sistema_comuni:
  - curl
  - htop
  - ufw

# Pacchetti APT nativi per Ubuntu 24.04 LTS necessari a far girare Docker e Ansible Docker Modules
pacchetti_app:
  - git
  - docker.io
  - docker-compose-v2
  - docker-buildx
  - python3-pip
  - python3-docker
  - python3-setuptools

pacchetti_db:
  - docker.io
  - python3-docker

db_conn:
  host: "192.168.1.73"
  port: 3306
  name: "menu_progetto"
  user: "menu"

lb_config:
  frontend_port: 80         # La porta su cui risponderà il servizio web finale
  stats_port: 8080          # La porta per vedere la tua dashboard dei nodi
  stats_uri: "/stats"       # Il percorso della pagina web delle statistiche

app_config:
  git_repo: "https://{{ lookup('env', 'GIT_TOKEN') }}@github.com/MartinaZelli/menu_v2.0.git"
  git_version: "main"
