progetto_docker: "progetto_menu"
destinazione: "/opt"
modalita_developer: false
package_update: true

utility_sistema_comuni:
  - curl
  - htop
  - ufw

# Pacchetti APT nativi per Ubuntu 24.04 LTS necessari a far girare Docker e Ansible Docker Modules
pacchetti_app:
  - git
  - docker.io
  - docker-compose-v2
  - docker-buildx
  - python3-pip
  - python3-docker
  - python3-setuptools

pacchetti_db:
  - docker.io
  - python3-docker

ip:
  app1_ip: "{{ lookup('env', 'APP1_IP') }}"
  app2_ip: "{{ lookup('env', 'APP2_IP') }}"
  db_ip: "{{ lookup('env', 'DB_IP') }}"
  lb_ip: "{{ lookup('env', 'LB_IP') }}"

db_conn:
  host: "{{ lookup('env', 'DB_HOST') }}"
  port: 3306
  name: "menu_progetto"
  user: "menu"
  volume_path: "{{ lookup('env', 'DB_VOLUME_PATH') }}"
  pass: "{{ lookup('env', 'DB_PASSWORD') }}"
  root_pass: "{{ lookup('env', 'DB_ROOT_PASSWORD') }}"

lb_config:
  frontend_port: "{{ lookup('env', 'LB_FRONTEND_PORT') }}"
  stats_port: "{{ lookup('env', 'LB_STATS_PORT') }}"
  stats_uri: "{{ lookup('env', 'LB_STATS_URI') | default('/stats', true) }}"
  check_path: "{{ lookup('env', 'LB_CHECK_PATH') }}"
  maxconn: "{{ lookup('env', 'LB_MAXCONN') | default('20000', true) }}"
  timeout_connect: "{{ lookup('env', 'LB_TIMEOUT_CONNECT') | default('5000', true) }}"
  timeout_client: "{{ lookup('env', 'LB_TIMEOUT_CLIENT') | default('50000', true) }}"
  timeout_server: "{{ lookup('env', 'LB_TIMEOUT_SERVER') | default('50000', true) }}"
  algorithm: "{{ lookup('env', 'LB_ALGORITHM') | default('roundrobin', true) }}"

app_config:
  git_repo: "https://{{ lookup('env', 'GIT_TOKEN') }}@{{ lookup('env', 'GIT_REPO') }}"
  git_version: "main"
  port: "{{ lookup('env', 'APP_CONFIG_PORT') | default('8000', true) }}"
