---

- name: Installazione e preconfigurazione di slapd
  ansible.builtin.import_tasks: install.yml
  tags: [ldap_install]

- name: Crea struttura e utenti della directory
  ansible.builtin.import_tasks: structure.yml
  tags: [ldap_structure]

- name: Configurazione TLS del server LDAP
  ansible.builtin.import_tasks: tls.yml
  when: ldap_server_tls_enabled
  tags: [ldap_tls]
