---

- name: Crea le unità organizzative (contenitori)
  community.general.ldap_entry:
    server_uri: "ldap://localhost/"
    bind_dn: "cn=admin,{{ ldap_server_base_dn }}"
    bind_pw: "{{ ldap_server_admin_password }}"
    dn: "ou={{ item }},{{ ldap_server_base_dn }}"
    objectClass: organizationalUnit
    attributes:
      ou: "{{ item }}"
  loop:
    - people
    - groups


- name: Crea gli utenti (inetOrgPerson)
  community.general.ldap_entry:
    server_uri: "ldap://localhost/"
    bind_dn: "cn=admin,{{ ldap_server_base_dn }}"
    bind_pw: "{{ ldap_server_admin_password }}"
    dn: "uid={{ item.uid }},ou=people,{{ ldap_server_base_dn }}"
    objectClass: inetOrgPerson
    attributes:
      uid: "{{ item.uid }}"
      cn: "{{ item.cn }}"
      sn: "{{ item.sn }}"
      mail: "{{ item.mail }}"
      userPassword: "{{ lookup('env', item.password_env) }}"
  loop: "{{ ldap_server_users }}"
  loop_control:
    label: "{{ item.uid }}"
  no_log: true

- name: Aggiungi gli attributi POSIX agli utenti (per il login di sistema)
  community.general.ldap_attrs:
    server_uri: "ldap://localhost/"
    bind_dn: "cn=admin,{{ ldap_server_base_dn }}"
    bind_pw: "{{ ldap_server_admin_password }}"
    dn: "uid={{ item.uid }},ou=people,{{ ldap_server_base_dn }}"
    state: exact
    attributes:
      objectClass:
        - inetOrgPerson
        - posixAccount
      uidNumber: "{{ item.uid_number }}"
      gidNumber: "{{ item.gid_number }}"
      homeDirectory: "/home/{{ item.uid }}"
      loginShell: "{{ item.login_shell }}"
  loop: "{{ ldap_server_users }}"
  loop_control:
    label: "{{ item.uid }}"

- name: Crea i gruppi POSIX (esistenza)
  community.general.ldap_entry:
    server_uri: "ldap://localhost/"
    bind_dn: "cn=admin,{{ ldap_server_base_dn }}"
    bind_pw: "{{ ldap_server_admin_password }}"
    dn: "cn={{ item.cn }},ou=groups,{{ ldap_server_base_dn }}"
    objectClass: posixGroup
    attributes:
      cn: "{{ item.cn }}"
      gidNumber: "{{ item.gid_number }}"
  loop: "{{ ldap_server_groups }}"
  loop_control:
    label: "{{ item.cn }}"

- name: Imposta i membri dei gruppi POSIX
  community.general.ldap_attrs:
    server_uri: "ldap://localhost/"
    bind_dn: "cn=admin,{{ ldap_server_base_dn }}"
    bind_pw: "{{ ldap_server_admin_password }}"
    dn: "cn={{ item.cn }},ou=groups,{{ ldap_server_base_dn }}"
    state: exact
    attributes:
      memberUid: "{{ item.members }}"
  loop: "{{ ldap_server_groups }}"
  loop_control:
    label: "{{ item.cn }}"
