---

- name: Crea le unità organizzative (contenitori)
  community.general.ldap_entry:
    server_uri: "ldap://localhost/"
    bind_dn: "cn=admin,{{ ldap_server_base_dn }}"
    bind_pw: "{{ ldap_server_admin_password }}"
    dn: "ou={{ item }},{{ ldap_server_base_dn }}"
    objectClass: organizationalUnit
    attributes:
      ou: "{{ item }}"
  loop:
    - people
    - groups


- name: Crea gli utenti (entry minima valida)
  community.general.ldap_entry:
    server_uri: "ldap://localhost/"
    bind_dn: "cn=admin,{{ ldap_server_base_dn }}"
    bind_pw: "{{ ldap_server_admin_password }}"
    dn: "uid={{ item.uid }},ou=people,{{ ldap_server_base_dn }}"
    objectClass: inetOrgPerson
    attributes:
      uid: "{{ item.uid }}"      # RDN: deve esserci
      cn: "{{ item.cn }}"        # MUST (ereditato da person)
      sn: "{{ item.sn }}"        # MUST (ereditato da person)
  loop: "{{ ldap_server_users }}"
  loop_control:
    label: "{{ item.uid }}"

- name: Gestisci attributi mutabili e classe POSIX
  community.general.ldap_attrs:
    server_uri: "ldap://localhost/"
    bind_dn: "cn=admin,{{ ldap_server_base_dn }}"
    bind_pw: "{{ ldap_server_admin_password }}"
    dn: "uid={{ item.uid }},ou=people,{{ ldap_server_base_dn }}"
    state: exact
    attributes:
      objectClass: [inetOrgPerson, posixAccount]
      mail: "{{ item.mail }}"
      uidNumber: "{{ item.uid_number }}"
      gidNumber: "{{ item.gid_number }}"
      homeDirectory: "/home/{{ item.uid }}"
      loginShell: "{{ item.login_shell }}"
      cn: "{{ item.cn }}"
      sn: "{{ item.sn }}"
  loop: "{{ ldap_server_users }}"
  loop_control:
    label: "{{ item.uid }}"

- name: Imposta/aggiorna la password degli utenti
  community.general.ldap_attrs:
    server_uri: "ldap://localhost/"
    bind_dn: "cn=admin,{{ ldap_server_base_dn }}"
    bind_pw: "{{ ldap_server_admin_password }}"
    dn: "uid={{ item.uid }},ou=people,{{ ldap_server_base_dn }}"
    state: exact
    attributes:
      userPassword: "{{ lookup('vars', item.password_var) }}"
  loop: "{{ ldap_server_users }}"
  loop_control:
    label: "{{ item.uid }}"
  no_log: true # no_log: true è importante per evitare di esporre le password nei log di Ansible, anche se sono già protette da vault

- name: Crea i gruppi POSIX (esistenza)
  community.general.ldap_entry:
    server_uri: "ldap://localhost/"
    bind_dn: "cn=admin,{{ ldap_server_base_dn }}"
    bind_pw: "{{ ldap_server_admin_password }}"
    dn: "cn={{ item.cn }},ou=groups,{{ ldap_server_base_dn }}"
    objectClass: posixGroup
    attributes:
      cn: "{{ item.cn }}"
      gidNumber: "{{ item.gid_number }}"
  loop: "{{ ldap_server_groups }}"
  loop_control:
    label: "{{ item.cn }}"

- name: Imposta i membri dei gruppi POSIX
  community.general.ldap_attrs:
    server_uri: "ldap://localhost/"
    bind_dn: "cn=admin,{{ ldap_server_base_dn }}"
    bind_pw: "{{ ldap_server_admin_password }}"
    dn: "cn={{ item.cn }},ou=groups,{{ ldap_server_base_dn }}"
    state: exact
    attributes:
      memberUid: "{{ item.members }}"
  loop: "{{ ldap_server_groups }}"
  loop_control:
    label: "{{ item.cn }}"
