---
# PLAY 0: Cancellare le vecchie chiavi SSH per evitare problemi di connessione
- name: "Preparazione SSH | Pulisci le vecchie impronte digitali"
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Rimuovi la vecchia chiave SSH per la VM App
      ansible.builtin.known_hosts:
        name: "192.168.1.72"
        state: absent

    - name: Rimuovi la vecchia chiave SSH per la VM DB
      ansible.builtin.known_hosts:
        name: "192.168.1.73"
        state: absent

# PLAY 1: Configurazione comune del sistema su TUTTI i server (App e DB)
- name: "Inizializzazione Comune e Installazione Docker"
  hosts: all
  become: true
  roles:
    - progetto_menu

# PLAY 2: Configurazione specifica del Database sul server DB
- name: "Deploy del Database MySQL Isolato"
  hosts: db_servers
  become: true
  tasks:
    - name: "Esegui i task dedicati al database"
      ansible.builtin.include_tasks:
        file: roles/progetto_menu/tasks/database.yml

# PLAY 3: Configurazione specifica dell'App sul server App
- name: "Deploy dell'Applicazione FastAPI"
  hosts: app_servers
  become: true
  tasks:
    - name: "Esegui i task dedicati all'applicazione"
      ansible.builtin.include_tasks:
        file: roles/progetto_menu/tasks/progetto.yml

  # Includendo l'handler direttamente all'interno di questo Play,
  # risolviamo l'errore del handler non trovato durante il task Git.
  handlers:
    - name: Riavvia Docker
      ansible.builtin.systemd:
        name: docker
        state: restarted
      become: true
