---
- name: Configura il firewall sui nodi interni
  hosts: internal
  become: true
  roles:
    - firewall

- name: Configura il firewall sul Domain Controller
  hosts: domain_controllers
  become: true
  roles:
    - firewall
