---
# 1. Installazione del pacchetto HAProxy ufficiale nativo (senza Docker)
- name: load_balancer | Installa HAProxy nativamente sul sistema
  ansible.builtin.apt:
    name: haproxy
    state: present
  become: true

# 2. Apertura del firewall UFW per il traffico pubblico (Porta 80 e Porta Dashboard)
- name: load_balancer | Firewall - Consenti il traffico sulle porte HTTP e Stats
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  become: true
  loop:
    - "{{ lb_config.frontend_port }}"
    - "{{ lb_config.stats_port }}"

# 3. Generazione del file di configurazione partendo dal template Jinja2
- name: load_balancer | Inizializza haproxy.cfg base se non esiste
  ansible.builtin.template:
    src: haproxy_base.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
    force: "{{ lb_config.force_config }}"
  become: true
  notify: "Riavvia HAProxy"

# 2. Configura il backend FastAPI
- name: load_balancer | Inietta backend FastAPI
  ansible.builtin.blockinfile:
    path: /etc/haproxy/haproxy.cfg
    marker: "# {mark} {{ haproxy_markers.fastapi }}"
    block: "{{ lookup('template', 'backend_app.cfg.j2') }}"
    insertafter: EOF
  become: true
  notify: "Riavvia HAProxy"

# 3. Configura il backend MySQL
- name: load_balancer | Inietta backend MySQL
  ansible.builtin.blockinfile:
    path: /etc/haproxy/haproxy.cfg
    marker: "# {mark} {{ haproxy_markers.mysql_monitor }}"
    block: "{{ lookup('template', 'backend_db.cfg.j2') }}"
    insertafter: EOF
  become: true
  notify: "Riavvia HAProxy"

# 4. Assicura che il servizio sia abilitato al boot del sistema
- name: load_balancer | Assicura che HAProxy sia abilitato al boot
  ansible.builtin.systemd:
    name: haproxy
    enabled: true
  become: true
