---
- name: sistema | Aggiorna la cache dei pacchetti APT
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: sistema | Installa i pacchetti richiesti per Docker e Git
  ansible.builtin.apt:
    name: "{{ utility_sistema_comuni }}"
    state: "{{ 'latest' if package_update | bool else 'present' }}"
  become: true
