---

ldap_server_admin_password: "{{ lookup('env', 'LDAP_SERVER_ADMIN_PASSWORD') }}"


ldap_server_domain: "lab.home"          # da cui slapd deriva il base DN
ldap_server_organization: "Lab"         # attributo o: della radice
ldap_server_backend: "MDB"              # backend del database (LMDB)

ldap_server_base_dn: "dc={{ ldap_server_domain.split('.') | join(',dc=') }}"

# utenti da creare nella directory
ldap_server_users:
  - uid: mzelli
    cn: "Martina Zelli"
    sn: "Zelli"
    mail: "mzelli@lab.home"
    password_env: "LDAP_SERVER_USER_MZELLI_PASSWORD"
    uid_number: 10000          # ID utente Unix
    gid_number: 10000          # ID gruppo primario
    login_shell: /bin/bash

  - uid: esterno
    cn: "Utente Esterno"
    sn: "Esterno"
    mail: "esterno@lab.home"
    password_env: "LDAP_SERVER_USER_ESTERNO_PASSWORD"
    uid_number: 10001
    gid_number: 10001          # gruppo primario diverso da devops
    login_shell: /bin/bash

# gruppi da creare nella directory
ldap_server_groups:
  - cn: devops
    gid_number: 10000        # = il gidNumber primario di mzelli -> risolve il warning
    members:
      - mzelli

  - cn: esterni
    gid_number: 10001
    members:
      - esterno
# --- TLS ---
ldap_server_tls_enabled: true
ldap_server_fqdn: "ldap.{{ ldap_server_domain }}"   # ldap.lab.home (per i SAN)
ldap_server_ca_key: /etc/ldap/lab-ca.key
ldap_server_ca_cert: /etc/ldap/lab-ca.crt
ldap_server_tls_key: /etc/ldap/ldap.key
ldap_server_tls_cert: /etc/ldap/ldap.crt
ldap_server_tls_csr: /etc/ldap/ldap.csr
# Tengo tutto sotto /etc/ldap/ di proposito: è un percorso che il profilo AppArmor di slapd già consente in lettura
