---
- name: database | Installa i pacchetti Docker minimi per il motore standalone
  ansible.builtin.apt:
    name: "{{ pacchetti_db }}"
    state: "{{ 'latest' if package_update | bool else 'present' }}"
  become: true

- name: Aggiungi ubuntu al gruppo docker
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: true
  become: true

- name: database | Assicura che il servizio Docker sia avviato e abilitato al boot
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
  become: true

- name: database | Consenti le connessioni MySQL in ingresso da tutti i server applicativi
  community.general.ufw:
    rule: allow
    from_ip: "{{ hostvars[item]['ansible_host'] }}"
    port: '3306'
    proto: tcp
  become: true
  loop: "{{ groups['app_servers'] }}"

- name: database | Avvia il container MySQL ufficiale in modo isolato
  community.docker.docker_container:
    name: mysql_db
    image: mysql:8.0
    state: started
    restart_policy: always
    published_ports:
      - "3306:3306"
    env:
      MYSQL_ROOT_PASSWORD: "{{ db_config.root_pass }}"
      MYSQL_DATABASE: "{{ db_config.name }}"
      MYSQL_USER: "{{ db_config.user }}"
      MYSQL_PASSWORD: "{{ db_config.pass }}"
    volumes:
      # Sostituisci in futuro questo volume locale con il tuo Network Storage!
      - db_data:/var/lib/mysql
  become: true
