---
# 1. INSTALLAZIONE DELLO STACK APPLICATIVO
- name: progetto | Installa i pacchetti richiesti per Docker, Git e moduli Python
  ansible.builtin.apt:
    name: "{{ pacchetti_app }}"
    state: "{{ 'latest' if package_update | bool else 'present' }}"
  become: true

- name: Aggiungi ubuntu al gruppo docker
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: true
  become: true
  notify: Riavvia Docker

# 2. CONFIGURAZIONE DEL FIREWALL UFW (Esercizio di blindatura)
- name: progetto | Firewall - Consenti SSH (Porta 22)
  community.general.ufw:
    rule: allow
    name: OpenSSH
  become: true

- name: progetto | Firewall - Consenti porta 8000 SOLO dal server Load Balancer
  community.general.ufw:
    rule: allow
    from_ip: "{{ hostvars['menu-lb']['ansible_host'] }}"
    port: '8000'
    proto: tcp
  become: true

- name: progetto | Firewall - Imposta la policy di default in ingresso su DENY
  community.general.ufw:
    direction: incoming
    policy: deny
  become: true

- name: progetto | Firewall - Abilita UFW
  community.general.ufw:
    state: enabled
  become: true

# 3. CONTROLLO DI PRONTEZZA DEL DATABASE
- name: progetto | Attendi che la porta del database sia aperta e responsiva via rete
  ansible.builtin.wait_for:
    host: "{{ db_conn.host }}"
    port: "{{ db_conn.port }}"
    state: started
    delay: 3
    timeout: 60
    msg: "Il database su {{ db_conn.host }} non è pronto dopo 60 secondi. Interrompo il deployment dell'app."

# 4. DEPLOY E AVVIO DELL'APPLICAZIONE FASTAPI
- name: progetto | Crea directory di destinazione del progetto
  ansible.builtin.file:
    path: "{{ destinazione }}/{{ progetto_docker }}"
    state: directory
    mode: '0755'
  become: true

- name: progetto | Scarica codice Git repository v2.0
  ansible.builtin.git:
    repo: "{{ app_config.git_repo }}"
    dest: "{{ destinazione }}/{{ progetto_docker }}"
    version: "{{ app_config.git_version }}"
    force: true
  become: true

- name: progetto | Crea il file .env di configurazione per il database remoto
  ansible.builtin.copy:
    dest: "{{ destinazione }}/{{ progetto_docker }}/.env"
    content: |
      DB_HOST={{ db_conn.host }}
      DB_PORT={{ db_conn.port }}
      DB_NAME={{ db_conn.name }}
      DB_USER={{ db_conn.user }}
      DB_PASSWORD={{ db_secrets.pass }}
      HOST_IP={{ ansible_host }}
    mode: '0600'
  become: true

- name: progetto | Avvia e ricostruisci l'applicazione usando il modulo nativo Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ destinazione }}/{{ progetto_docker }}"
    services:
      - app
      - popola-db
    state: present
    build: "{{ 'always' if modalita_developer else 'policy' }}"
    recreate: "{{ 'always' if modalita_developer else 'auto' }}"
  become: true
  environment:
    HOST_IP: "{{ ansible_host }}"
