- name: progetto | Assicura che il servizio sia avviato e abilitato
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: progetto | Configura Docker per rispettare UFW (no iptables)
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "iptables": false
      }
    mode: '0644'
  become: true
  notify: "Riavvia Docker"

- name: progetto | Crea directory di destinazione
  ansible.builtin.file:
    path: "{{ destinazione }}/{{ progetto_docker }}"
    state: directory
    mode: '0755'

- name: progetto | Scarica codice Git repository v2.0
  ansible.builtin.git:
    repo: "https://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@github.com/MartinaZelli/menu_v2.0.git"
    dest: "{{ destinazione }}/{{ progetto_docker }}"
    version: "main"
    force: true
  become: true
  notify: "Riavvia Docker"

# Generiamo un file .env direttamente nella cartella clonata.
# L'applicazione FastAPI leggerà queste impostazioni puntando al DB della VM remota!
- name: progetto | Crea il file .env di configurazione per il database remoto
  ansible.builtin.copy:
    dest: "{{ destinazione }}/{{ progetto_docker }}/.env"
    content: |
      DB_HOST={{ db_config.host }}
      DB_PORT={{ db_config.port }}
      DB_NAME={{ db_config.name }}
      DB_USER={{ db_config.user }}
      DB_PASSWORD={{ db_config.pass }}
      HOST_IP={{ ansible_host }}
    mode: '0644'
  become: true

- name: progetto | Firewall - Consenti SSH (Porta 22)
  community.general.ufw:
    rule: allow
    name: OpenSSH
  become: true

- name: progetto | Firewall - Consenti porta 8000 SOLO da Load Balancer
  community.general.ufw:
    rule: allow
    from_ip: "{{ hostvars['menu-lb']['ansible_host'] }}"
    port: '8000'
    proto: tcp
  become: true

- name: progetto | Firewall - Nega porta 8000 a chiunque altro
  community.general.ufw:
    rule: deny
    port: '8000'
    proto: tcp
  become: true

- name: progetto | Firewall - Abilita UFW
  community.general.ufw:
    state: enabled
  become: true

- name: "Progetto : Avvia e ricostruisci l'applicazione usando il modulo nativo Docker"
  community.docker.docker_compose_v2:
    project_src: "{{ destinazione }}/{{ progetto_docker }}"
    services:
      - app
      - popola-db
    state: present
    build: "{{ 'always' if modalita_developer else 'auto' }}"     # <-- Sostituisce il flag "--build" se modalita_developer è true,
    recreate: "{{ 'always' if modalita_developer else 'auto' }}"  # <-- Sostituisce il flag "--force-recreate" se modalita_developer è true,
  become: true
  environment:
    HOST_IP: "{{ ansible_host }}"
  register: progetto_menu_docker_compose_output

- name: progetto | Mostra i log dettagliati di Docker Compose
  ansible.builtin.debug:
    var: progetto_menu_docker_compose_output
