- name: progetto | Assicura che il servizio sia avviato e abilitato
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: progetto | Crea directory di destinazione
  ansible.builtin.file:
    path: "{{ destinazione }}/{{ progetto_docker }}"
    state: directory
    mode: '0755'

- name: progetto | Scarica codice Git dal nuovo repository v2.0
  ansible.builtin.git:
    repo: "https://github.com/MartinaZelli/menu_v2.0.git"
    dest: "{{ destinazione }}/{{ progetto_docker }}"
    version: "main"
    force: true
  become: true
  notify: "Riavvia Docker"

# Generiamo un file .env direttamente nella cartella clonata.
# L'applicazione FastAPI leggerà queste impostazioni puntando al DB della VM remota!
- name: progetto | Crea il file .env di configurazione per il database remoto
  ansible.builtin.copy:
    dest: "{{ destinazione }}/{{ progetto_docker }}/.env"
    content: |
      DB_HOST={{ db_config.host }}
      DB_PORT={{ db_config.port }}
      DB_NAME={{ db_config.name }}
      DB_USER={{ db_config.user }}
      DB_PASSWORD={{ db_config.pass }}
    mode: '0644'
  become: true

- name: progetto | Avvia l'applicazione e il popolamento usando la CLI nativa
  ansible.builtin.command:
    cmd: "docker compose up -d --force-recreate --build app popola-db"
    chdir: "{{ destinazione }}/{{ progetto_docker }}"
  become: true

- name: progetto | Mostra i log dettagliati di Docker Compose
  ansible.builtin.debug:
    var: docker_compose_output  # <--- Stampa a schermo tutto l'output verboso
